# Generated by Django 5.0 on 2024-01-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
