# Generated by Django 5.0 on 2024-01-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
