# Generated by Django 5.0 on 2023-12-20 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sprite', 'Sprite'), ('coke', 'Coke'), ('pepsi', 'Pepsi'), ('chicken', 'Chicken'), ('beef', 'Beef'), ('fufu', 'Fufu'), ('soup', 'Soup')], max_length=150, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='static/extra_icons')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rice', [('fried rice', 'Fried'), ('jollof rice', 'Jollof'), ('rice ofe akwu', 'Ofe Akwu')]), ('Soup', [('oha soup', 'Oha'), ('egusi soup', 'Egusi')]), ('Snack', [('meat pie', 'Meat Pie'), ('sharwama chicken', 'Sharwama (Chicken)'), ('sharwama beef', 'Sharwama (Beef)')])], max_length=150, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/food_icons')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('extras', models.ManyToManyField(to='spicita.extra')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spicita.dish')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.extra')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('address', models.TextField(max_length=300)),
                ('note', models.TextField(blank=True, max_length=300)),
                ('ordered', models.BooleanField(default=False, editable=False)),
                ('delivered', models.BooleanField(default=False, editable=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dishes', models.ManyToManyField(through='spicita.Amount', to='spicita.dish')),
                ('extras', models.ManyToManyField(blank=True, through='spicita.Amount', to='spicita.extra')),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spicita.order'),
        ),
    ]
