# Generated by Django 5.0 on 2023-12-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='quantity',
        ),
        migrations.AddField(
            model_name='amount',
            name='num_dish',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amount',
            name='num_extra',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
