# Generated by Django 5.0 on 2023-12-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0002_remove_amount_quantity_amount_num_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='qu',
            field=models.BinaryField(null=True),
        ),
    ]
