# Generated by Django 5.0 on 2023-12-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0003_amount_qu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('extra_quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('dish', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.dish')),
                ('extra', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.extra')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='spicita.orderitem'),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
