# Generated by Django 5.0 on 2023-12-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0004_remove_order_extras_remove_order_dishes_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.dish'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.extra'),
        ),
    ]
