# Generated by Django 5.0 on 2023-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0006_orderitem_order_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(editable=False, to='spicita.orderitem'),
        ),
    ]
