# Generated by Django 5.0 on 2023-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0007_remove_orderitem_order_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Total Price of Order'),
        ),
    ]
