# Generated by Django 5.0 on 2023-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0008_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1000, editable=False, verbose_name='Total Price of Order'),
            preserve_default=False,
        ),
    ]
