# Generated by Django 5.0 on 2023-12-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0009_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='tprice',
        ),
    ]
