# Generated by Django 5.0 on 2023-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0011_alter_order_tprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tprice',
            field=models.PositiveIntegerField(editable=False, verbose_name='Total Price of Order'),
        ),
    ]
