# Generated by Django 5.0 on 2023-12-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0012_alter_order_tprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tprice',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Total Price of Order'),
            preserve_default=False,
        ),
    ]
