# Generated by Django 5.0 on 2023-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0013_remove_order_tprice_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='tprice',
            field=models.PositiveIntegerField(default=100, editable=False, verbose_name='Total Price of Order'),
            preserve_default=False,
        ),
    ]
