# Generated by Django 5.0 on 2023-12-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0014_remove_order_price_order_tprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tprice',
        ),
    ]
