# Generated by Django 5.0 on 2023-12-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0015_remove_order_tprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Total Price of Order (Naira)'),
            preserve_default=False,
        ),
    ]
