# Generated by Django 5.0 on 2023-12-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0016_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
    ]
