# Generated by Django 5.0 on 2023-12-20 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0017_remove_orderitem_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spicita.dish'),
        ),
    ]
