# Generated by Django 5.0 on 2024-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0018_orderitem_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(choices=[('Drinks', [('sprite', 'Sprite'), ('coke', 'Coca-Cola'), ('pepsi', 'Pepsi')]), ('Rice', [('chicken', 'Chicken'), ('beef', 'Beef')]), ('Soup', [('fufu', 'Fufu'), ('soup', 'Soup'), ('sauce', 'Sauce')])], max_length=150, null=True, unique=True),
        ),
    ]
