# Generated by Django 6.0.3 on 2026-03-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0021_alter_order_customer'),
        ('users', '0003_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(choices=[('Drinks', [('sprite', 'Sprite'), ('coke', 'Coca-Cola'), ('pepsi', 'Pepsi')]), ('Rice', [('chicken', 'Chicken'), ('beef', 'Beef')]), ('Soup', [('fufu', 'Fufu'), ('soup', 'Soup'), ('sauce', 'Sauce')])], default='extra name', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
