# Generated by Django 6.0.3 on 2026-03-18 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spicita", "0022_alter_extra_name_alter_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="dish_quantity",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="extra",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="extra_quantity",
        ),
        migrations.AddField(
            model_name="extra",
            name="dishes",
            field=models.ManyToManyField(to="spicita.dish"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spicita.order"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="extra",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="order_items", to="spicita.orderitem"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spicita.dish"
            ),
        ),
        migrations.CreateModel(
            name="OrderItemExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spicita.extra"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spicita.orderitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="extras",
            field=models.ManyToManyField(to="spicita.orderitemextra"),
        ),
    ]
