# Generated by Django 6.0.3 on 2026-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0023_remove_orderitem_dish_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/extra_icons'),
        ),
    ]
