# Generated by Django 6.0.3 on 2026-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0024_alter_extra_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='extras',
            field=models.ManyToManyField(blank=True, to='spicita.extra'),
        ),
    ]
