# Generated by Django 6.0.3 on 2026-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicita', '0026_remove_order_items_remove_orderitem_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='food_icons'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='extra_icons'),
        ),
    ]
